### ISSUE TITLE
Checking link to video with hash anchor results in `NotImplementedError`/`AssertionError`

### ISSUE THREAD

**Issue by timobrembeck** [DjangoAdminHackers/django-linkcheck#150]
Checking an mp4 video with hash anchor caused the error: `NotImplementedError: subclasses of ParserBase must override error()` with the following traceback:

```
Checking all links that haven't been tested for 10080 minutes.
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/bin/integreat-cms-cli", line 53, in <module>
    main()
  File "/opt/integreat-cms/.venv/bin/integreat-cms-cli", line 49, in main
    execute_from_command_line(sys.argv)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/management/commands/checklinks.py", line 35, in handle
    external_checked = check_links(external_recheck_interval=externalinterval, limit=limit, check_internal=False)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/utils.py", line 116, in check_links
    status = u.check_url(check_internal=check_internal, check_external=check_external)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/models.py", line 182, in check_url
    self._check_external(self.url, external_recheck_interval)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/models.py", line 328, in _check_external
    self._check_anchor(anchor, response.text, internal=False)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/models.py", line 337, in _check_anchor
    names = parse_anchors(html)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/linkcheck/__init__.py", line 98, in parse_anchors
    parser.feed(content)
  File "/usr/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.9/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.9/html/parser.py", line 263, in parse_html_declaration
    return self.parse_marked_section(i)
  File "/usr/lib/python3.9/_markupbase.py", line 149, in parse_marked_section
    sectName, j = self._scan_name( i+3, i )
  File "/usr/lib/python3.9/_markupbase.py", line 390, in _scan_name
    self.error("expected name token at %r"
  File "/usr/lib/python3.9/_markupbase.py", line 33, in error
    raise NotImplementedError(
NotImplementedError: subclasses of ParserBase must override error()
```

I could reproduce this problem with any direct video link followed by a hash anchor, e.g.:

https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4#t=1.0

Python: 3.9.2
Django: 3.2.16
django-linkcheck: 2.0.0

**Comment by timobrembeck** [comment]
I just noticed that the ultimate `NotImplementedError` was indeed a bug of python itself: https://bugs.python.org/issue31844

On Python 3.10 and newer (https://github.com/python/cpython/commit/e34bbfd61f405eef89e8aa50672b0b25022de320), it throws an `AssertionError` instead and the traceback looks e.g. as follows:
```
Checking all links that haven't been tested for 10080 minutes.
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/bin/integreat-cms-cli", line 53, in <module>
    main()
  File "/opt/integreat-cms/.venv/bin/integreat-cms-cli", line 49, in main
    execute_from_command_line(sys.argv)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/management/commands/checklinks.py", line 35, in handle
    external_checked = check_links(external_recheck_interval=externalinterval, limit=limit, check_internal=False)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/utils.py", line 116, in check_links
    status = u.check_url(check_internal=check_internal, check_external=check_external)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/models.py", line 182, in check_url
    self._check_external(self.url, external_recheck_interval)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/models.py", line 328, in _check_external
    self._check_anchor(anchor, response.text, internal=False)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/models.py", line 337, in _check_anchor
    names = parse_anchors(html)
  File "/opt/integreat-cms/.venv/lib/python3.10/site-packages/linkcheck/__init__.py", line 98, in parse_anchors
    parser.feed(content)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 263, in parse_html_declaration
    return self.parse_marked_section(i)
  File "/usr/lib/python3.10/_markupbase.py", line 154, in parse_marked_section
    raise AssertionError(
AssertionError: unknown status keyword 'H' in marked section
```

I managed to trace back the problem to d45fb6212c213db5877bd34fcda52f24cf600284 where I changed a bare `except` to an `except UnicodeDecodeError` which apparently did not cover all possible exceptions.

**Comment by claudep** [comment]
I wonder if we may check the response content type and not try to run `_check_anchor` on non-text content. We can still keep the new exception catching you introduced (as content-type can be faked), but that would avoid most of the time trying to parse big binary content.
