### ISSUE TITLE
Failed building wheel for django-linkcheck

### ISSUE THREAD

**Issue by Oxicode** [DjangoAdminHackers/django-linkcheck#83]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0308' in position 32: character maps to <undefined>

**Comment by andybak** [comment]
Is there a line number in that error?

**Comment by winpat** [comment]
I've ran into the same (or a similar) problem.
```
root@65538a1ba8fb:/# pip3 install django-linkcheck
Collecting django-linkcheck
  Downloading https://files.pythonhosted.org/packages/6d/28/13af28aafbe643d31420f64641ebbe4d625c5944863308f11889979535ba/django-linkcheck-1.5.tar.gz
Building wheels for collected packages: django-linkcheck
  Running setup.py bdist_wheel for django-linkcheck ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ulv_ae5x/django-linkcheck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0pt7_w1cpip-wheel- --python-tag cp35:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 3407: ordinal not in range(128)
Call stack:
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 810, in build
    python_tag=python_tag,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 686, in _build_one
    if self.__build_one(req, tempd, python_tag=python_tag):
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 721, in __build_one
    show_stdout=False, spinner=spinner)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 721, in call_subprocess
    '\n----------------------------------------'
Message: 'running bdist_wheel\nrunning build\nrunning build_py\ncreating build\ncreating build/lib\ncreating build/lib/linkcheck\ncopying linkcheck/apps.py -> build/lib/linkcheck\ncopying linkcheck/utils.py -> build/lib/linkcheck\ncopying linkcheck/listeners.py -> build/lib/linkcheck\ncopying linkcheck/cron.py -> build/lib/linkcheck\ncopying linkcheck/linkcheck_settings.py -> build/lib/linkcheck\ncopying linkcheck/settings.py -> build/lib/linkcheck\ncopying linkcheck/admin_blocks.py -> build/lib/linkcheck\ncopying linkcheck/dashboard.py -> build/lib/linkcheck\ncopying linkcheck/__init__.py -> build/lib/linkcheck\ncopying linkcheck/views.py -> build/lib/linkcheck\ncopying linkcheck/urls.py -> build/lib/linkcheck\ncopying linkcheck/models.py -> build/lib/linkcheck\ncreating build/lib/linkcheck/management\ncopying linkcheck/management/__init__.py -> build/lib/linkcheck/management\ncreating build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/findlinks.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checkexternal.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checklinks.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checkinternal.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/__init__.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/unignore_links.py -> build/lib/linkcheck/management/commands\ncreating build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0001_initial.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0003_redirect_to_as_textfield.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/__init__.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0002_url_redirect_to.py -> build/lib/linkcheck/migrations\ncreating build/lib/linkcheck/tests\ncopying linkcheck/tests/__init__.py -> build/lib/linkcheck/tests\ncopying linkcheck/tests/test_linkcheck.py -> build/lib/linkcheck/tests\ncopying linkcheck/tests/urls.py -> build/lib/linkcheck/tests\ncreating build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/linklists.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/__init__.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/views.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/models.py -> build/lib/linkcheck/tests/sampleapp\ncreating build/lib/linkcheck/templates\ncreating build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/report.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/coverage.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/suggested_linklist.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/suggested_configs.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/base_linkcheck.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/paginator.xhtml -> build/lib/linkcheck/templates/linkcheck\ncreating build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/found -> build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/r\xfcckmeldung -> build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/ru\u0308ckmeldung -> build/lib/linkcheck/tests/media\ninstalling to build/bdist.linux-x86_64/wheel\nrunning install\nrunning install_lib\ncreating build/bdist.linux-x86_64\ncreating build/bdist.linux-x86_64/wheel\ncreating build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/apps.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/utils.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/listeners.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncreating build/bdist.linux-x86_64/wheel/linkcheck/management\ncreating build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/findlinks.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checkexternal.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checklinks.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checkinternal.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/unignore_links.py -> build/bdist.linux-x86_64/wheel/linkcheck/management/commands\ncopying build/lib/linkcheck/management/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck/management\ncreating build/bdist.linux-x86_64/wheel/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0001_initial.py -> build/bdist.linux-x86_64/wheel/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0003_redirect_to_as_textfield.py -> build/bdist.linux-x86_64/wheel/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0002_url_redirect_to.py -> build/bdist.linux-x86_64/wheel/linkcheck/migrations\ncreating build/bdist.linux-x86_64/wheel/linkcheck/templates\ncreating build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/report.html -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/coverage.html -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/suggested_linklist.html -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/suggested_configs.html -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/paginator.xhtml -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/base_linkcheck.html -> build/bdist.linux-x86_64/wheel/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/cron.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/linkcheck_settings.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/settings.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/admin_blocks.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/dashboard.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/views.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/urls.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncopying build/lib/linkcheck/models.py -> build/bdist.linux-x86_64/wheel/linkcheck\ncreating build/bdist.linux-x86_64/wheel/linkcheck/tests\ncreating build/bdist.linux-x86_64/wheel/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/found -> build/bdist.linux-x86_64/wheel/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/r\xfcckmeldung -> build/bdist.linux-x86_64/wheel/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/ru\u0308ckmeldung -> build/bdist.linux-x86_64/wheel/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests\ncopying build/lib/linkcheck/tests/test_linkcheck.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests\ncopying build/lib/linkcheck/tests/urls.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests\ncreating build/bdist.linux-x86_64/wheel/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/linklists.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/__init__.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/views.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/models.py -> build/bdist.linux-x86_64/wheel/linkcheck/tests/sampleapp\nrunning install_egg_info\nrunning egg_info\ncreating django_linkcheck.egg-info\nwriting django_linkcheck.egg-info/PKG-INFO\nwriting dependency_links to django_linkcheck.egg-info/dependency_links.txt\nwriting top-level names to django_linkcheck.egg-info/top_level.txt\nwriting manifest file \'django_linkcheck.egg-info/SOURCES.txt\'\n\'linkcheck/tests/media/r\\udcc3\\udcbcckmeldung\' not utf-8 encodable -- skipping\n\'linkcheck/tests/media/ru\\udccc\\udc88ckmeldung\' not utf-8 encodable -- skipping\nreading manifest file \'django_linkcheck.egg-info/SOURCES.txt\'\nwriting manifest file \'django_linkcheck.egg-info/SOURCES.txt\'\nCopying django_linkcheck.egg-info to build/bdist.linux-x86_64/wheel/django_linkcheck-1.5.egg-info\nrunning install_scripts\ncreating build/bdist.linux-x86_64/wheel/django_linkcheck-1.5.dist-info/WHEEL\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/tmp/pip-build-ulv_ae5x/django-linkcheck/setup.py", line 43, in <module>\n    \'Framework :: Django\',\n  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup\n    dist.run_commands()\n  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands\n    self.run_command(cmd)\n  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command\n    cmd_obj.run()\n  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 236, in run\n    self.write_record(self.bdist_dir, self.distinfo_dir)\n  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 453, in write_record\n    writer.writerow((record_path, hash, size))\nUnicodeEncodeError: \'ascii\' codec can\'t encode characters in position 24-25: ordinal not in range(128)\n\n----------------------------------------'
Arguments: ()
  Failed building wheel for django-linkcheck
  Running setup.py clean for django-linkcheck
Failed to build django-linkcheck
Installing collected packages: django-linkcheck
  Running setup.py install for django-linkcheck ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ulv_ae5x/django-linkcheck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wvdrpps3-record/install-record.txt --single-version-externally-managed --compile:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 3507: ordinal not in range(128)
Call stack:
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 721, in call_subprocess
    '\n----------------------------------------'
Message: 'running install\nrunning build\nrunning build_py\ncreating build\ncreating build/lib\ncreating build/lib/linkcheck\ncopying linkcheck/apps.py -> build/lib/linkcheck\ncopying linkcheck/utils.py -> build/lib/linkcheck\ncopying linkcheck/listeners.py -> build/lib/linkcheck\ncopying linkcheck/cron.py -> build/lib/linkcheck\ncopying linkcheck/linkcheck_settings.py -> build/lib/linkcheck\ncopying linkcheck/settings.py -> build/lib/linkcheck\ncopying linkcheck/admin_blocks.py -> build/lib/linkcheck\ncopying linkcheck/dashboard.py -> build/lib/linkcheck\ncopying linkcheck/__init__.py -> build/lib/linkcheck\ncopying linkcheck/views.py -> build/lib/linkcheck\ncopying linkcheck/urls.py -> build/lib/linkcheck\ncopying linkcheck/models.py -> build/lib/linkcheck\ncreating build/lib/linkcheck/management\ncopying linkcheck/management/__init__.py -> build/lib/linkcheck/management\ncreating build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/findlinks.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checkexternal.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checklinks.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/checkinternal.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/__init__.py -> build/lib/linkcheck/management/commands\ncopying linkcheck/management/commands/unignore_links.py -> build/lib/linkcheck/management/commands\ncreating build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0001_initial.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0003_redirect_to_as_textfield.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/__init__.py -> build/lib/linkcheck/migrations\ncopying linkcheck/migrations/0002_url_redirect_to.py -> build/lib/linkcheck/migrations\ncreating build/lib/linkcheck/tests\ncopying linkcheck/tests/__init__.py -> build/lib/linkcheck/tests\ncopying linkcheck/tests/test_linkcheck.py -> build/lib/linkcheck/tests\ncopying linkcheck/tests/urls.py -> build/lib/linkcheck/tests\ncreating build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/linklists.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/__init__.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/views.py -> build/lib/linkcheck/tests/sampleapp\ncopying linkcheck/tests/sampleapp/models.py -> build/lib/linkcheck/tests/sampleapp\ncreating build/lib/linkcheck/templates\ncreating build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/report.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/coverage.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/suggested_linklist.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/suggested_configs.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/base_linkcheck.html -> build/lib/linkcheck/templates/linkcheck\ncopying linkcheck/templates/linkcheck/paginator.xhtml -> build/lib/linkcheck/templates/linkcheck\ncreating build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/found -> build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/r\xfcckmeldung -> build/lib/linkcheck/tests/media\ncopying linkcheck/tests/media/ru\u0308ckmeldung -> build/lib/linkcheck/tests/media\nrunning install_lib\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/apps.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/utils.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/listeners.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/management\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/findlinks.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checkexternal.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checklinks.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/checkinternal.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/commands/unignore_links.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands\ncopying build/lib/linkcheck/management/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/management\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0001_initial.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0003_redirect_to_as_textfield.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/migrations\ncopying build/lib/linkcheck/migrations/0002_url_redirect_to.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/migrations\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/templates\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/report.html -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/coverage.html -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/suggested_linklist.html -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/suggested_configs.html -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/paginator.xhtml -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/templates/linkcheck/base_linkcheck.html -> /usr/local/lib/python3.5/dist-packages/linkcheck/templates/linkcheck\ncopying build/lib/linkcheck/cron.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/linkcheck_settings.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/settings.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/admin_blocks.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/dashboard.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/views.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/urls.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncopying build/lib/linkcheck/models.py -> /usr/local/lib/python3.5/dist-packages/linkcheck\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/tests\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/found -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/r\xfcckmeldung -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/media/ru\u0308ckmeldung -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/media\ncopying build/lib/linkcheck/tests/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests\ncopying build/lib/linkcheck/tests/test_linkcheck.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests\ncopying build/lib/linkcheck/tests/urls.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests\ncreating /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/linklists.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/__init__.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/views.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp\ncopying build/lib/linkcheck/tests/sampleapp/models.py -> /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/apps.py to apps.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/utils.py to utils.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/listeners.py to listeners.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/findlinks.py to findlinks.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/checkexternal.py to checkexternal.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/checklinks.py to checklinks.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/checkinternal.py to checkinternal.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/commands/unignore_links.py to unignore_links.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/management/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/migrations/0001_initial.py to 0001_initial.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/migrations/0003_redirect_to_as_textfield.py to 0003_redirect_to_as_textfield.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/migrations/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/migrations/0002_url_redirect_to.py to 0002_url_redirect_to.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/cron.py to cron.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/linkcheck_settings.py to linkcheck_settings.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/settings.py to settings.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/admin_blocks.py to admin_blocks.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/dashboard.py to dashboard.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/views.py to views.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/urls.py to urls.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/models.py to models.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/test_linkcheck.py to test_linkcheck.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/urls.py to urls.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp/linklists.py to linklists.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp/__init__.py to __init__.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp/views.py to views.cpython-35.pyc\nbyte-compiling /usr/local/lib/python3.5/dist-packages/linkcheck/tests/sampleapp/models.py to models.cpython-35.pyc\nrunning install_egg_info\nrunning egg_info\nwriting dependency_links to django_linkcheck.egg-info/dependency_links.txt\nwriting top-level names to django_linkcheck.egg-info/top_level.txt\nwriting django_linkcheck.egg-info/PKG-INFO\n\'linkcheck/tests/media/r\\udcc3\\udcbcckmeldung\' not utf-8 encodable -- skipping\n\'linkcheck/tests/media/ru\\udccc\\udc88ckmeldung\' not utf-8 encodable -- skipping\nreading manifest file \'django_linkcheck.egg-info/SOURCES.txt\'\nwriting manifest file \'django_linkcheck.egg-info/SOURCES.txt\'\nCopying django_linkcheck.egg-info to /usr/local/lib/python3.5/dist-packages/django_linkcheck-1.5.egg-info\nrunning install_scripts\nwriting list of installed files to \'/tmp/pip-wvdrpps3-record/install-record.txt\'\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/tmp/pip-build-ulv_ae5x/django-linkcheck/setup.py", line 43, in <module>\n    \'Framework :: Django\',\n  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup\n    dist.run_commands()\n  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands\n    self.run_command(cmd)\n  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command\n    cmd_obj.run()\n  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run\n    return orig.install.run(self)\n  File "/usr/lib/python3.5/distutils/command/install.py", line 610, in run\n    self.record)\n  File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute\n    util.execute(func, args, msg, dry_run=self.dry_run)\n  File "/usr/lib/python3.5/distutils/util.py", line 301, in execute\n    func(*args)\n  File "/usr/lib/python3.5/distutils/file_util.py", line 236, in write_file\n    f.write(line + "\\n")\nUnicodeEncodeError: \'ascii\' codec can\'t encode characters in position 62-63: ordinal not in range(128)\n\n----------------------------------------'
Arguments: ()
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ulv_ae5x/django-linkcheck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wvdrpps3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ulv_ae5x/django-linkcheck/
root@65538a1ba8fb:/#

```

**Comment by winpat** [comment]
@Oxicode in my case, I've used an old version of pip which caused the issue. (pip 9.0.1 failed, 18.0 seems to work)

**Comment by fruitschen** [comment]
Closing this one, as upgrading pip solves the problem.
